version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: athlete_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: athlete_performance
    ports:
      - "5432:5432"
    volumes:
      - ./sql/createdb.sql:/docker-entrypoint-initdb.d/create_db.sql
      - postgres_data:/var/lib/postgresql/data
  
  rest_service:
    build: ./fastapi_rest
    container_name: athlete_rest_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=athlete_performance
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  grpc_service:
    build: ./node_grcp
    container_name: athlete_grpc_api
    restart: always
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=athlete_performance
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  graphql_service:
    build: ./node_graphql
    container_name: athlete_graphql_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - GRAPHQL_PORT=4000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=athlete_performance
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: iot_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: iot_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: iot_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always

volumes:
  postgres_data: